apiVersion: "cilium.io/v2"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "first-pool"
spec:
  blocks:
    - start: "{{talos_loadbalancer_start_ip}}"
      stop: "{{talos_loadbalancer_end_ip}}"

---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: policy1
spec:
  serviceSelector:
    matchLabels:
      io.cilium/lb-enabled: "true"
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
  interfaces:
    - ^eth[0-9]+
  externalIPs: true
  loadBalancerIPs: true
