---
talos_loadbalancer_start_ip: "10.10.61.50"
talos_loadbalancer_end_ip: "10.10.61.59"

talos_shared_gateway_ip: "10.10.61.51"

talos_cilium_network: 10.224.0.0/13
talos_cilium_node_network_size: 22

talos_shared_gateway_corp_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  63623933383534323831633232313337373363623064323433323432656564666236383830613635
  6433636636323066333339616635326463653865383365640a323730333637663563643638336532
  66333635613662356365303633316363383561336238666662323535353864656366623461346661
  6234663264396634350a373638653361373862363664313331373439383535336535333833393564
  39663235316162353934646230626633636563623231356236626538643039363136356263663333
  30373530396161396435323834316333633065393963336434306135646464663436303864623730
  35623339326133333839343365383637666537363133383836653232343832343066336634316131
  34323163396663623932386566396237633932346262633135376265313463303363336339333766
  38343836353434333134623564306530366364653437333938623030356330666563313836636437
  62363935653033663865666137643134323964636162383537376636333838306362366361353135
  35616661313739363230333132373766313631343362353039323039383563653036303665663664
  62653339623861353932626236326164356335663431613066343630313439646439616631313032
  65663561656133353863653639376264663633353662326363303338666630313865326565346131
  62316131353631616630626663633733613563393034633263343839663431346364363837313364
  34366438313532303233353964353863313339373564613032646432373566663835346465616566
  62343838393966393437

talos_shared_gateway_com_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  62373965626433656330353536653732373063353135346666303963353636633861386534366236
  6330663264343635323336316532353166656532316332610a376165343865353865353537336432
  61343733656363623038393963373834396536623737656664356366376336316566363865326637
  6234346562333732660a383032663533316562663163626465643737353434353438663161366234
  31366637343562633339343162336631393064666532313865366231383563343237663936333231
  30303665663234636135343662653838306434323937366239366139613066643765326339393633
  62316538626335303563326562396136393832393531353339626661343062333537663761323036
  63633930613266306632396331666363376464343130626431623965666264396666356439393537
  33323638393538646563663530336532366331336530646464653930306235363336623934333761
  33353132396264633263626463626330666663333761323565656631313238323730653832663330
  34623830376230626331666566313137346132303862333865393830326236626661396561356532
  63666236616163393436343535353637626566633064643035366138616135313864393737343531
  36633939666439633464326366363761326130306362616336306563376331333262336238613064
  63626138383662636534353831643832656431336461313935313465323634623730343633363035
  39303034393066646436333635666131626536383138643165623832336136626565326434393937
  61643630343363363865306137343133373230326132303033626634613035646261326235333564
  62653539316462376563623138363466336336313233303865633965333936623237363466613333
  36346335643362623939376132633036303439663963306466613365616235616335363262633137
  61306638343531303737346631323331333033623862316133306666313665356664383564303035
  35616465313965383162336139383831623161663630316131333165636362343537376235643535
  62626665333434383634663762393334623534646563356263643861613062373532626531366337
  32386562633636353337303165636665346334316263386238663065653865343261623133663666
  64306661353430623238313261303362666432353766643362343830636534356431643036663730
  33623164373330366134623932323264663535353531343833393032623832363231343465326164
  37333739646533373265333261643566316566313663386336353831666235666664386230636531
  62393466643462366130393062383937396134363661323234323337613164396264653730373862
  64643538643135643836326431313032396264323266613436616635363061623864366163613138
  36616261646366633162353737366139636364306232323062343735363662623830636532383361
  39303239313039363937313065646436393832343563636634373230363662373235363064363232
  38326235633535666462356266656639393831366264336335656262396463336561643034366335
  33623565356132316163653631363237303163653566383166366163383337333538333365663830
  37663137646333323534353961326137313964633061303363373466626332323664306134323564
  64316365306634643134303033303562643962653637623832643039326666376461306465633964
  32376262643562633334633330666665643334346238346636633631386636363739646536356236
  38616262663336393131636339323235396132333632643436336166666337373865313863356433
  33393536643633336362323562303630346536343335396531316638373165343165633931656539
  34666166383162626434373832303934613463396333613831313531303662633638666336353132
  37366631663361623938333238323133343561653037306565313964373632396331376366623032
  39373833333234336166393066643938326662626434653837303763393364353265363231313139
  62346332316236643834633837616466623562656231346534613164303631343738353261303639
  31323135616564643338353736363639313539613534376163653932633962613134653132613963
  32313338353062636631383435353033653361323837313834326636636363353137313536653461
  32323366383932356364343933333933393061383132653535313739653661353039643638333463
  35313062356261623830373266636539623830313938373333366233666566626630303036306534
  39636639323565336464653232373532303465366464396133666564653932343636373962663663
  65383634323139393538396263656332303562376532646438313165666635663365623561306664
  31383339323861353864626237346563633833366135636534653666366135343933363565313336
  36633039636164643638376534323732663166363638393131346366316135316561303331336432
  34346366313539663736393530623936313534613332373562353630383961636461353339646538
  39633364313236623733666132636636313339376361626537643832656561646562383438343061
  62643038653364386632616262386431343936393930316538653039353963376237306538313964
  63356262303433656132346232376565663633626538363932396130663037653638396461643235
  63626238653566343039383730366335346235343435346436663863616538336435343731386562
  30333864656534356438653731636539613733613636643336366131303064323034383738393639
  38633262353937366638343565303761616135383262366237353365393664333032623665343739
  35383130616130633261343261383166616437653430313635626163336532363936346337376234
  61346265616339343866666434353633646539616437636438303536336234393861353539633934
  61653136393235343536313864623531343832313566373163383061653135313136366363313161
  37353565663762373064643339383530363733333938636266353562663037356332633239633034
  32373830333937316363666538623834623464643561613130613138353035633366663338663738
  39623338303439616539366539663134343439666265653065306164393238323863626561383465
  33613732333566326334656436353961396363383063336138643634353737633833653336313366
  35353835616366636333353061653230346233346261343933613466373134653239393538346639
  38633265623165383936623433653632303539383830626637386335336435383339386536333532
  31366461356364643964396139343639376466343765383561623930326362346663623063323335
  38383337353265306236653262376337313333386634333164363836343461386364303365393266
  62386434346635366132626263323061366162393631366261373765613133326332326232333834
  39373639643332346366663135393536333139323562323861303432383531613838363566613331
  31643539333330633062646666366538346236623631333338643437613132663834366635633266
  34323639366530616564313461663066353966633739613464653236623738303364333434656630
  36656430613430356561623864393262353138626562623063343766336336313065656137393866
  32613833363636303034656633643430373534626430326164366131666232633538643866653739
  63633038316464316365326165343438616564393762396562303332353837366666353366623731
  34366262346632616238623933633262366439316333313934326562356437316137383230313438
  63373764346361623363396534313763383537646163333834653463656230626333393963653732
  61353733363630376132356130663735633134643534396234666339353738376561326235633436
  37323030623033633637346338343137353262346366643262333237633731383631623533373663
  62366430356237656539646531333934653864346631383134303564353564643362306530376165
  65616135613066396664356639626230313865643537366236653033383436613436663463616364
  63336662663534636531333337383965323665636432343138313733393335616562376138636237
  31333836346238326339666338316536353235353139633436663538383264313032353132646232
  65383439633166333536326439636334366164356637336434366532313534383961373535356433
  30373230663338646261616439353265653263613036653934643532666566393533323039626434
  30323039353232623335653833383631313532383464326536346365373438313331336333653639
  36326564343266633637633836363337353966323337633466623931353535643964383037643233
  37363964396235346539613535363265626461363463363362366238373165316339323466373461
  61373838383638653331623866623362346632366439333466326362393031336639303131326631
  62383634633563306630366565383137353166363338373834653861323539646662366338313039
  66366437393231343937653365326265316365633135333733663462613732376262616536373233
  36643964383134383131353361333064643933346266303034373538653332366533663333616232
  35623663616363646639333437343732626539373363626164646638306663306565313563393034
  39613830396638396361663931353662353261326131323461353933333932636365666333313138
  36653135663930326235333761383431636462313637663265373463636237376462356333656637
  30343039643030356533353539336465346435646234343364383035386339636263626535386333
  64613731623665383039353832653830303662623936336439366231356338623938393132623861
  36663630386130646465393838653761393935363731353336646262373734356439306537316632
  34353936393663363535316666326236633030346664373136663732643230616530363137626636
  61316365663637393064633435393938343564663566333632326339396330626438353939633864
  63613666386263626530616530623932623565653538323562653561393263626663333439343335
  38386664663831366461373132616633613438623732656332663638343839653566393837363837
  63393130613364313837653234393465623366323032613631613166393031356537353163333266
  37663239336636336165346361376539633633386632636133316461623230303130386262336135
  38633536353238646437313335366662366131653538356564336565326230373165303339373562
  34666463626634376264363233393764313730353561336532386262383135316537613934376532
  36323838653036366634646431666262613131323637643131336139636437323337373666373561
  65313261356331613739643866633430613132613466313635363939643762333436313462333433
  37323237363930613534323361666664366136653839306435353765663539333237323837346162
  62316662346438643336623435623061383331316332323766356462313738306465393437346363
  63323863613633353230323562326265663238396435643534313463656537306666363839353764
  65653565316232316435646538376432323165333361646564316261303333333239386635313035
  37326264636366386561373531643536653730323830356364393935346133643237633333643434
  65373363366161653161663665313563396361363934396437353733643737306266666132353030
  65396161313762373065353365363131336365353437336135346631666364313239313864316431
  66383562393764613666303634363763663261336435613430376338373933373634333332666137
  34383534656230306630386430646662373163663032626237653130386662336633643130353266
  39616230386631393265613537386663353463623566363261316536616539323239303838336662
  64363264323239663333646661313838623631653232616435373439353566313133353637663834
  66313230666166653333623862613835666339376664643132373435303336366137356635353866
  37333038653136656238353163613236313439366234373031626262643032376362346238386138
  33333734346438393366323831356462343433623739336530646632643439363439343934366137
  66623439303839643837323939316464313763643436336239313136356663363862363365373337
  34666239333938356532623030656563643435653666623135363965343333366238393633346464
  34633136316439386237646461663436393762616366613366346632656531393433653166663035
  30313137306262623134353537313535653833323032386561623965316134656332333936303262
  33326535646162623666663333643866323436623263303865616663636331666139323866326539
  32376635303039336130656534316439323465633233393638363763393037363762656534616239
  37303230313836613061393338636236346435373138306630383365393333326461623764623930
  61346239633063376362373566333661303433656438336633623663373566323864663430626562
  30316166306438303534316330393463326536636463333436376365643834643334353731326462
  35386631633633326631386337346664663639643963346434653766336166373465313162343964
  32613533393865636234653365306466306538313931653333643138616266343539353263303438
  66666134383531666334336466393636356636373163656363333534383265323737386138326333
  37383366363031643663663135306163393065663137353162303137373934393631336430303731
  33393465653034653766626263343632663133623239323235373765303431666466666235383836
  34653065386638626330366464303238313265313036306234623139633265636263313762643236
  31383966303265316565306333623764383462633637366436363863633965626366643931616238
  34303433613531363135306130623839626437313936616433396335393862393230643665303534
  33376339393330323662373837666161383439346239356332656566643233636264626432323534
  37363439336138383938393964666532343163636465633261323436363438303566343735336132
  33396633653033326362323761316334363635646530393439313662613334303436663261666638
  63363636393734343366643130336135313534646634303339363764353637636239366664323935
  35646235353264613766326166373534653231663964326236373537373361656566346632373435
  66316462323761333737636566666431353466343432323564313031623330326538346534343665
  61303862613634613731396633343463613031343536303862346138323865633531313638623638
  35366636303439623337303735336161323731396431383662323164616564616536336135396364
  36383365306564353837343437313539613366383037626439333039633563303561656465386532
  36313431396662333834383264386161353833346537663961363366613162653238346462376366
  33393635633136316538313934656232656530363263653938303263383365346430323335353834
  64643037306561346232346266646638613964373465343361393663366433643537623730333430
  62613938613233623162393030633234653462333264646431333961643264333862366435663566
  39323864656662306561633761626562393638393630663634643330313732306534353731346238
  30316365383138386565323730383365633566616534353637653761306461363361623734353461
  61343634616364616631656631313737316134353062626532393361613737613165306636313831
  39663932326534636539633231363961643231636366373866316239633532626631653030626262
  65653638343766366538333963623364353032393230393166643961663866386633356334356661
  34373430656238306166303463663431313962646361343033363837313064336539383261343964
  35356666343836663032633231306333666664346366333037333335653465643239643065346162
  30623334333166383135306462663633333638376332346238383034363837346130306332373265
  63393332336633396566646331333764626339356365663930346133623331323661643234636334
  39306662353163616362306639363136363064623762656365323364363063643666376161336464
  65613439663832616235393238386138353836336333316561646564333530393636373835353235
  66663734613138646330643935356635376465356334353436353361353931343231643130366130
  32613262666436633339383166633464353531633737653336363935636234323237316632313133
  34383835323566323434396661393730633836613431643164316538393463353262623530613236
  63646535663936356637323864613762386263373336333932353764373336643935623961343862
  61613666336634613534313337353838376533643732623634356533356166653362663636626633
  62353539643764383763316536313932333938366538333563303431633739386366623962346664
  34623033343738373133
